### ISSUE TITLE
Variations and commentary

### ISSUE THREAD

**Issue by daylen** [daylen/stockfish-mac#10]
Support reading PGN files with variations and commentary. This would involve changing the internal representation of chess games in `SFMChessGame` from an `NSMutableArray` of move objects into a tree with node objects that can hold subtrees and comments (for that node).

**Comment by boompig** [comment]
+1

**Comment by amilner42** [comment]
+1

Basically makes this GUI unusable for me if I can't enter variations...

**Comment by adriang133** [comment]
I am planning to try implement this in the near future.

**Comment by shreyasminocha** [comment]
Would it be possible to implement adding and analysing variations from the app?

**Comment by daylen** [comment]
@shreyasminocha You can add variations in version 2.1, which is in the Mac App Store. Go to a position where you'd like to add a variation and play a different move than what was played. You'll get the option to overwrite or add variation.

**Comment by shreyasminocha** [comment]
@daylen I'm sorry, I thought I was running the latest version because the app store didn't tell me there was an update. Cheers.
