### ISSUE TITLE
App closes immediately after pressing go in app store version on big sur

### ISSUE THREAD

**Issue by Juesto** [daylen/stockfish-mac#100]
im running this on a late 2014 mac mini and there's no report a problem dialog coming up at all

trying to run the engines directly in the terminal says Illegal instruction: 4

**Comment by daylen** [comment]
First of all, sorry for the year-long turnaround on this bug! Wondering if you're still experiencing this issue -- I'm not sure why this is happening (nor do I have a Late 2014 Mac Mini to test this) but it's possible that upgrading to a newer version of macOS might resolve this.

**Comment by Juesto** [comment]
unfortunately monterey causes lag, my main system is catalina currently.
well, the minimum is big sur.
wish the minimum was lowered 
thanks for the response @daylen

**Comment by daylen** [comment]
If you're comfortable with using Xcode, you could clone this repo, build the engine yourself, and use that build as a replacement for the engine included in this repo. I suspect there's some incompatibilities cross-compiling for a different architecture and OS even though I'm using all the right flags. (I'm building for Intel on a 2024 M3 MacBook Air…)

My make command is just: `make -j build ARCH=x86-64-sse41-popcnt` and the Stockfish engine repo is https://github.com/official-stockfish/Stockfish

**Comment by Juesto** [comment]
hmmm strange, thank you
