### ISSUE TITLE
Notation should be clickable

### ISSUE THREAD

**Issue by foshaug** [daylen/stockfish-mac#22]
The notation should be clickable and update the board to reflect the position at that time.

**Comment by zbeekman** [comment]
this would be a fantastic addition

**Comment by timothyha** [comment]
+1
The notation from analysis is not clickable at the moment.

**Comment by adriang133** [comment]
Create a PR for this.

**Comment by timothyha** [comment]
> The notation from analysis is not clickable at the moment.
The new version 2.1 has variations and notations clickable from the PGN content, but not from the Stockfish variations part.

**Comment by adriang133** [comment]
I don't think that having engine analysis clickable would be a good UX. Not even sure how it would work. Imagine you click on some move in a variation shown by the engine. Then after a few seconds that variation is demoted and not even visible in the UI anymore. How do you handle this ? you would have a position on the board but you don't have any visual clue where it comes from etc. 

And if you look at other chess GUIs like Chessbase/Fritz they also don't have clickable engine analysis.

**Comment by timothyha** [comment]
@adriang133  - thanks, Adrian, that makes sense.  Thanks for the work, too!
