### ISSUE TITLE
Stockfish reports draw even though it is opposite side to move

### ISSUE THREAD

**Issue by PunkSage** [daylen/stockfish-mac#26]
I have played following sequence of moves:
1. Qe6+ Rf7 2. Qc8+ Kg7 3. Qc3+ Kf8 4. Qc8+ Kg7 5. Kg2 Kf6 6. Kf3 Ke5+ 7. Ke3 Kf6 8. Qc3+ Ke7 9. Qc5+ Kd7 10. Ke4 Rf6 11. Ke5 Rh6 12. Qb5+ Kc7 13. Kd4 Rh4+ 14. Kc3 Kd6 15. Qd3+ Ke5 16. Qe2+ Re4 17. Qb5+ Kf4 18. Qf1+ Ke5 19. Qf2 Ke6 20. Qb6+ Kf7 21. Qb3+ Kf6 22. Qd5 Re7 23. Kd4 Kg7 24. Qg5+ Kf8 25. Kd5 Rb7 26. Ke6 Rb6+ 27. Kd7 Rb7+ 28. Kc6 Rg7 29. Qf5+ Rf7 30. Qg6 Rf2 31. Kd6 Rd2+ 32. Ke5 Rd7 33. Qf5+ Rf7 34. Qc8+ Kg7 35. Ke6 Rf6+ 36. Ke7 Rf4 37. Qc3+ Kg6 38. Qg3+ Kf5 39. Qd3+ Ke5 40. Qd6+ Ke4 41. Qc6+ Kd3 42. Qd5+ Kc3 43. Qe5+ Rd4 44. Qe1+ Kc2 45. Qg3 Rd1 46. Qe3 Rc1 47. Kd6 Ra1 48. Qd4 Rb1 49. Kc5 Rc1 50. Kb4 Ra1 51. Qf2+ Kb1 52. Kc3 Ra2 53. Qf5+ Ka1 54. Qf1# 

On move 50. Ra1 played by Stockfish it reported that 'It's a draw' even though it was my turn to play. However after clicking 'Ok' I was able to finish mating sequence.

**Comment by PunkSage** [comment]
I have noticed that it due to 50 move draw rule. Is there any way to turn it off?

**Comment by daylen** [comment]
There's no way to turn it off at the moment.
