### ISSUE TITLE
Incorrect Pawn Promotion query

### ISSUE THREAD

**Issue by mbrna** [daylen/stockfish-mac#29]
Using version 2.0.4 (21), in this position:
q5k1/5p2/p5pp/3bp1b1/Pp1n4/1P1P1P1P/2rN2P1/1NBQR1K1 w Kk - 0 1

If White selects the king for a move, the program shows that the white king can move to where he currently sits (in addition to his 4 possible moves), AND if the king moves to h1 the program offers pawn promotion?!?

Note that if the following FEN is loaded:
q5k1/5p2/p5pp/3bp1b1/Pp1n4/1P1P1P1P/2rN2P1/1NBQR1K1 w - - 0 1

the program behaves correctly.

**Comment by daylen** [comment]
The first FEN is invalid (the white king has left its original square so there shouldn't be any castling rights) so the behavior is undefined.

**Comment by mbrna** [comment]
Ok. That brings up two questions. 

A) I generated the FEN from stockfish so that I could include it here. Should stockfish generate invalid FEN strings?

and

B) If it is an invalid FEN why does stockfish load it?  

Kf1 works in that situation. 

Seems to me there is a bug there somewhere. Kh1 is a valid move in that situation regardless of whether white is allowed to castle or not. 

=== michael brna ===
