### ISSUE TITLE
Bug in cmd-D "Do best move"?

### ISSUE THREAD

**Issue by caesss** [daylen/stockfish-mac#37]
When Cmd-D (do best move) is pressed you get this screen? this is not in the prod version is there a reason for this screen? 
cancel works, create variation also works but overwrite crashes the app. 
![screen shot 2017-12-18 at 9 57 08 pm](https://user-images.githubusercontent.com/1952297/34140237-f647317a-e43e-11e7-83dd-a49e688fb232.png)

**Comment by adriang133** [comment]
There was a small issue with doBestMove. Fixed in #38.

**Comment by caesss** [comment]
thank you. your code fixes the issue.

**Comment by caesss** [comment]
Thank you for your quick response @adriang133 Consider taking a look at "doMoveWithOverwritePrompt" it appears that your code is crashing when this is called now. I'm not sure if I should open a new issue or keep it here since your fix affected the other function. Thank you again.

**Comment by adriang133** [comment]
Can you please be more specific about reproducing this ? I couldn't do it.

I am making a few moves, reopening, previous moves are there, I start engine analysis. 
What do you mean by "do move" ? Is that Do Best Move ? I tried it and it works fine for me. I also tried overwrite a few times and it seems to work.

**Comment by caesss** [comment]
Let me know if this helps. The crash actually comes from file /Stockfish/Chess/position.cpp, line 772.
By the way, I'm using: Xcode 9.2, MacOS HighSierra and the latest Stockfish Engine binaries in case that makes a difference. 
![stockfish](https://user-images.githubusercontent.com/1952297/34209825-5c59702a-e559-11e7-9162-28fa082090ec.gif)

**Comment by adriang133** [comment]
I still could not reproduce that for some reason. Are you sure you're on the latest commit ? And can you maybe try with the binaries that are included in this repo ? (though I doubt this can have anything to do with it)

I have found another bug however, when trying to reproduce yours. For me the analysis still stays on the second ply, but I did not have time to investigate yesterday.

**Comment by caesss** [comment]
that's strange, yes I downloaded the whole thing again just to make sure. The only thing I can think of is to make sure the engine is "running" while you are making the overwrite move. If the engine is not running the error doesn't happen but it does crash when it is active.

**Comment by adriang133** [comment]
I think I was actually getting the error but for some reason it just showed up in XCode while the execution continued. Maybe it's because I played with some XCode settings or it's just the newer XCode version... 

It was a bug where the game state was updated wrongly when you overwrite a move.
I fixed it in the same PR, can you please confirm ?

**Comment by caesss** [comment]
@adriang133 That does it. I appreciate your work. I will keep looking through the code to see if I can help but I'm more of Swift guy. I'm closing the ticket now and I hope @daylen does the merge soon. Thank you again!
