### ISSUE TITLE
Crash when reverting changes

### ISSUE THREAD

**Issue by shreyasminocha** [daylen/stockfish-mac#40]
On Stockfish for Mac 2.1, when I add a variation and then close the app selecting "Revert changes", the app freezes. I'm running macOS Sierra Version 10.12.6.

**Comment by adriang133** [comment]
What is revert changes ? I see no such thing when closing the app.

**Comment by shreyasminocha** [comment]
I'm talking about this:
![screenshot 2018-01-07 at 16 44 28](https://user-images.githubusercontent.com/11537232/34648919-19057a92-f3ca-11e7-86a8-0ecb82e6fe92.JPEG)

**Comment by shreyasminocha** [comment]
On testing it for the third time, it seems to be working fine. That's strange. I'll see if I have this problem in the future and close this issue otherwise.

**Comment by daylen** [comment]
Closing because cannot duplicate
