### ISSUE TITLE
Unable to read moves beyond pawn promotion

### ISSUE THREAD

**Issue by shreyasminocha** [daylen/stockfish-mac#41]
I'm running version 2.1 on macOS Sierra version 10.12.6. I tried to load a game with pawn promotion. The game loads and everything goes well until the pawn promotion and the game after that doesn't load. I created a separate `.pgn` to verify this:

```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "1-0"]
[WhiteElo ""]
[BlackElo ""]
[ECO ""]
[FEN "3k4/8/6P1/4K3/8/8/8/8 w - - 0 1"]
[SetUp "1"]
[CurrentPosition "6Q1/4k3/8/4K3/8/8/8/8 b - - 2 2"]

1.g7 Ke7 2.g8=Q  1-0
```

![screenshot 2018-01-05 at 23 32 36](https://user-images.githubusercontent.com/11537232/34621846-c2745a40-f270-11e7-8816-d9450137fba3.JPEG)

**Comment by adriang133** [comment]
The move regex used doesn't have support for promotions. See #44

**Comment by daylen** [comment]
Closing because #44 is merged
