### ISSUE TITLE
PGN games with promotions are truncated

### ISSUE THREAD

**Issue by snicolet** [daylen/stockfish-mac#45]
Hi Daylen,

There seem to be a problem when opening a PGN file with a collection of games, as the games which contain a promotion to Queen at move n are truncated to move (n-1): the promotion and the subsequent moves are not parsed.

 I have attached a zip archive which contains a PGN file demonstrating the problem.

Steps to reproduce the bug:

• unzip the zip archive
• open the file "bug.pgn" in a editor and note that game 2 has a promotion to Queen by Black at move #48, but ends at move #103 
• drag the file "bug.pgn" on the Stockfish icon in the dock
• play out the moves of the second game in the list (White:base Black:stockfish Result:0-1)

=> the game is truncated to move #48.

And thanks for the nice Stockfish app !
Sincerely yours,
Stéphane Nicolet

[bug.pgn.zip](https://github.com/daylen/stockfish-mac/files/1669206/bug.pgn.zip)

**Comment by adriang133** [comment]
This was already fixed(#41, #44). Are you running from the lastest source ?

**Comment by snicolet** [comment]
@adriang133 
Nope, I'm running version 2.1.1 (23) from the AppStore. I haven't compiled from the ObjectiveC sources (working on the engine is enough :-)) Thanks for having already fixed that in #41 and #44 (I suppose it is OK, though I can't check it).

**Comment by daylen** [comment]
Should be fixed now that 2.1.2 is on the store.
