### ISSUE TITLE
Crash upon opening PGN from FICS

### ISSUE THREAD

**Issue by pedestrianlove** [daylen/stockfish-mac#50]
As title stated.
Running on Macbook Air early 2015, El Capitan, OS X
Using the newest build on the App Store.

**Comment by pedestrianlove** [comment]
The PGN file is fine, since I've tested it with SCIDvsPC.

**Comment by adriang133** [comment]
Can you post the PGN file ?

**Comment by pedestrianlove** [comment]
Sorry, since I no longer have access to my PGN file, I'll close this issue instead.
Great thanks for your help!
