### ISSUE TITLE
Feature Request: Use of ARMv8 NEON intrinsics (M1 silicon)

### ISSUE THREAD

**Issue by kylhuk** [daylen/stockfish-mac#76]
To speed up calculations, the use of ARMv8/NEON intrinsics is important. Apple will focus solely on the ARM architecture in the future, thus porting from AVX2 to NEON is not a dead end, but maybe an opportunity.

**Comment by daylen** [comment]
The Stockfish engine already uses NEON intrinsics. See https://github.com/official-stockfish/Stockfish/blob/master/src/nnue/nnue_common.h#L70-L72.

**Comment by kylhuk** [comment]
@daylen Thanks for clearing that up. When I saw the following line in the readme, I thought NEON was not supported

```
* System hardware detection to load 64-bit, SSE4.2, or Haswell binaries
```

**Comment by daylen** [comment]
Oh yeah that readme is a bit out of date... I'll update it soon
