### ISSUE TITLE
Draw Bug

### ISSUE THREAD

**Issue by danispringer** [daylen/stockfish-mac#97]
Putting a KvsK+Q position on the board, with weaker king to move, and the only legal move being to capture the queen, which results in an immediate draw, has the app calculating forever... Even though as soon the next move is played it alerts "game over! draw", and after that it actually still allows making moves, and after every single move still alerts "game over, draw".

While if the position is, for example, a mate in 1, it quickly calculates till depth 245 (on my Mac at least, not sure what limits are), immediately saying it's M1, and not calculating for even a second more.

This does all feel like unexpected behavior...

Thanks

<img width="951" alt="Screenshot 2023-05-07 at 3 19 17 AM" src="https://user-images.githubusercontent.com/19246409/236663750-4a931359-a6ce-4eb9-9ddf-36776325973e.png">

**Comment by DaniSpringer** [comment]
Did this issue get archived?

**Comment by daylen** [comment]
This is an artifact of the engine, not the app. Closing as won't fix.
