### ISSUE TITLE
Stockfish Update (v16)

### ISSUE THREAD

**Issue by danispringer** [daylen/stockfish-mac#99]
Hi,
Any way I can help to update the app to use the updated version (16) of the engine?
Thanks

**Comment by danispringer** [comment]
@daylen seems this was done?

Thanks

**Comment by danispringer** [comment]
@daylen should I close this?
Thanks!

**Comment by daylen** [comment]
Closing, this was done in 7934f49a14e7824c4380dd1dbcbcb9e64a392bc8
